version: '3.3'

services:
  mongodb:
    image: bitnami/mongodb:4.4.8
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: construcao

  api:
    image: node:12
    container_name: api
    build: . 
    environment:
      - SECRET=245770ea-c13c-4dd5-b1d5-27467d7a231e
      - DATABASE_URI=mongodb://mongodb:27017/construcao
      - API_URL=api
      - CLASS_URL=http://<<<host>>>:3333/turma
    ports:
      - "3000:3000"
    command: bash -c "npm install -g n && n 12.13.0 && n which 12.13.0 && n prune && npm install && npm start"
    depends_on:
      - "mongodb"
